"""
RAG bypass attack mode: attempts to fool Layer 2 semantic RAG-based
vulnerability detection by generating code that is semantically distant
from known vulnerable examples in the RAG knowledge base.

Attack strategies:
  1. Domain shift — use domain-specific terminology not present in training data.
  2. Abstraction elevation — wrap the vulnerable operation in business-logic
     abstractions that obscure the underlying security-relevant call.
  3. Paraphrase injection — use synonymous code constructs from different ORMs
     or frameworks that the RAG index may not cover.
  4. False context — surround the vulnerable code with abundant safe-looking
     context (comments, validation, logging) to dilute the semantic signal.
"""

from __future__ import annotations

import re
import uuid
from dataclasses import dataclass, field
from typing import Any


@dataclass
class RAGBypassResult:
    """
    Result of a single RAG bypass attempt.

    Attributes:
        attempt_id: UUID for this attempt.
        vuln_class: Targeted vulnerability class.
        strategy: The bypass strategy employed.
        code: Generated bypass code.
        bypassed: True if RAG returned 'safe' for genuinely vulnerable code.
        rag_verdict: What the RAG system returned.
        ground_truth: Ground truth label.
        similarity_score: Cosine similarity to nearest known-vulnerable example.
        notes: Human-readable explanation.
    """

    attempt_id: str
    vuln_class: str
    strategy: str
    code: str
    bypassed: bool
    rag_verdict: str
    ground_truth: str
    similarity_score: float | None
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "attempt_id": self.attempt_id,
            "vuln_class": self.vuln_class,
            "strategy": self.strategy,
            "code": self.code,
            "bypassed": self.bypassed,
            "rag_verdict": self.rag_verdict,
            "ground_truth": self.ground_truth,
            "similarity_score": self.similarity_score,
            "notes": self.notes,
        }


# Domain-specific bypass templates that use unusual vocabulary/frameworks
_RAG_BYPASS_TEMPLATES: dict[str, list[tuple[str, str]]] = {
    "idor": [
        (
            "peewee_orm_direct_lookup",
            """
# Using Peewee ORM (less common in RAG training data)
from peewee import ModelSelect

def get_record_{uid}(record_id: int):
    \"\"\"Retrieve a client record by primary key.\"\"\"\
    return ClientRecord.get_by_id(record_id)  # no ownership check
""",
        ),
        (
            "sqlmodel_direct",
            """
from sqlmodel import Session, select

def load_profile_{uid}(session: Session, profile_id: int):
    \"\"\"Load user profile — internal service use only.\"\"\"\
    return session.get(Profile, profile_id)
""",
        ),
        (
            "false_context_idor",
            """
import logging
from typing import Optional

logger = logging.getLogger(__name__)

def get_order_details_{uid}(
    request_context: dict,
    order_identifier: int,
    include_archived: bool = False
) -> Optional[dict]:
    \"\"\"
    Retrieve order details for display in the customer portal.

    Args:
        request_context: Contains session metadata (logged, not validated).
        order_identifier: Primary key of the order record.
        include_archived: Whether to include archived orders.

    Returns:
        Order dict or None if not found.
    \"\"\"
    logger.info(f'Fetching order {{order_identifier}} for context {{request_context.get(\"session_id\")}}')
    # Direct lookup — ownership assumed to be verified at API gateway layer
    order = Order.objects.get(pk=order_identifier)
    logger.debug(f'Order retrieved: {{order.id}}')
    return order.to_dict()
""",
        ),
    ],
    "sqli": [
        (
            "aiosqlite_fstring",
            """
import aiosqlite

async def search_products_{uid}(db_path: str, keyword: str) -> list:
    \"\"\"Search product catalogue.\"\"\"\
    async with aiosqlite.connect(db_path) as db:
        cursor = await db.execute(
            f'SELECT id, name FROM products WHERE name LIKE \"%{{keyword}}%\"'
        )
        return await cursor.fetchall()
""",
        ),
        (
            "databases_library_fstring",
            """
import databases

async def find_user_{uid}(database: databases.Database, email: str) -> dict:
    query = f\"SELECT * FROM users WHERE email = '{{email}}'\"
    return await database.fetch_one(query=query)
""",
        ),
    ],
    "ssrf": [
        (
            "aiohttp_no_validation",
            """
import aiohttp

async def fetch_data_{uid}(endpoint_url: str) -> dict:
    \"\"\"Fetch data from configured endpoint.\"\"\"\
    async with aiohttp.ClientSession() as session:
        async with session.get(endpoint_url) as resp:
            return await resp.json()
""",
        ),
        (
            "tornado_httpclient",
            """
from tornado.httpclient import AsyncHTTPClient

async def proxy_request_{uid}(target: str) -> str:
    \"\"\"Proxy a request to the target URL.\"\"\"\
    client = AsyncHTTPClient()
    response = await client.fetch(target)
    return response.body.decode()
""",
        ),
    ],
    "path_traversal": [
        (
            "anyio_path_open",
            """
import anyio

async def read_config_{uid}(config_name: str) -> str:
    \"\"\"Read configuration file.\"\"\"\
    config_path = anyio.Path(f'/app/configs/{{config_name}}')
    return await config_path.read_text()
""",
        ),
    ],
    "auth_bypass": [
        (
            "starlette_no_auth",
            """
from starlette.requests import Request
from starlette.responses import JSONResponse

async def get_user_data_{uid}(request: Request) -> JSONResponse:
    \"\"\"Return user data — auth handled by Cloudflare layer.\"\"\"\
    user_id = request.path_params['user_id']
    user = await UserRepository.get(user_id)
    return JSONResponse(user.dict())
""",
        ),
    ],
}


class RAGBypassAttack:
    """
    Attempts to bypass Layer 2 semantic RAG-based vulnerability detection.

    A RAG-based detector retrieves semantically similar code examples from a
    knowledge base and uses their labels to classify new code. This attack
    exploits gaps in RAG coverage by generating code that:
      (a) Uses uncommon ORMs/frameworks not present in the knowledge base.
      (b) Dilutes the vulnerability signal with abundant safe-looking context.
      (c) Raises the abstraction level to obscure the underlying insecure call.

    Attributes:
        rag_detector: Optional callable `(code: str) -> dict` for the real RAG.
        n_iterations: Number of attack iterations.
    """

    def __init__(
        self,
        rag_detector: Any | None = None,
        n_iterations: int = 10,
    ) -> None:
        """
        Initialise the RAG bypass attacker.

        Args:
            rag_detector: Optional RAG detection callable.
            n_iterations: Number of attack iterations.

        Raises:
            ValueError: If n_iterations is not a positive integer.
        """
        if not isinstance(n_iterations, int) or n_iterations < 1:
            raise ValueError(f"n_iterations must be a positive integer, got {n_iterations}")
        self.rag_detector = rag_detector
        self.n_iterations = n_iterations
        self._results: list[RAGBypassResult] = []

    def run(self, vuln_class: str = "idor") -> dict[str, Any]:
        """
        Run the full RAG bypass attack loop.

        Args:
            vuln_class: Vulnerability class to target.

        Returns:
            Dict with n_bypasses, bypass_rate, bypasses, and all attempts.
        """
        if not isinstance(vuln_class, str):
            raise TypeError(f"vuln_class must be str, got {type(vuln_class).__name__}")
        if vuln_class not in _RAG_BYPASS_TEMPLATES:
            raise ValueError(f"No templates for vuln_class={vuln_class!r}")

        self._results.clear()
        templates = _RAG_BYPASS_TEMPLATES[vuln_class]
        bypass_count = 0

        for i in range(self.n_iterations):
            strategy_desc, template_code = templates[i % len(templates)]
            uid = str(uuid.uuid4()).replace("-", "_")[:8]
            code = template_code.format(uid=uid)

            rag_out = self._query_rag(code)
            rag_verdict = rag_out.get("label", "safe")
            sim_score = rag_out.get("similarity_score")
            ground_truth = self._oracle(code, vuln_class)
            bypassed = ground_truth == "vulnerable" and rag_verdict == "safe"
            if bypassed:
                bypass_count += 1

            self._results.append(
                RAGBypassResult(
                    attempt_id=str(uuid.uuid4()),
                    vuln_class=vuln_class,
                    strategy=strategy_desc,
                    code=code,
                    bypassed=bypassed,
                    rag_verdict=rag_verdict,
                    ground_truth=ground_truth,
                    similarity_score=sim_score,
                    notes=f"{'BYPASS' if bypassed else 'Detected'} via {strategy_desc}",
                )
            )

        bypass_rate = bypass_count / self.n_iterations if self.n_iterations else 0.0
        return {
            "vuln_class": vuln_class,
            "n_iterations": self.n_iterations,
            "n_bypasses": bypass_count,
            "bypass_rate": round(bypass_rate, 4),
            "bypasses": [r.to_dict() for r in self._results if r.bypassed],
            "attempts": [r.to_dict() for r in self._results],
        }

    def _query_rag(self, code: str) -> dict[str, Any]:
        """Query the RAG detector (or simulate)."""
        if self.rag_detector is not None:
            try:
                return self.rag_detector(code)
            except Exception:
                pass
        return self._simulated_rag(code)

    def _simulated_rag(self, code: str) -> dict[str, Any]:
        """Simulate RAG: only catches the most common Django ORM / requests patterns."""
        known_patterns = [
            r"objects\.get\s*\(\s*id\s*=",
            r"requests\.get\s*\(",
            r"execute\s*\(\s*f['\"]",
            r"open\s*\(\s*os\.path\.join",
        ]
        for pattern in known_patterns:
            if re.search(pattern, code, re.IGNORECASE):
                return {"label": "vulnerable", "similarity_score": 0.85}
        # RAG does not match unusual frameworks → low similarity → predicts safe
        return {"label": "safe", "similarity_score": 0.15}

    def _oracle(self, code: str, vuln_class: str) -> str:
        """Simple ground-truth oracle."""
        unsafe_signals = {
            "idor": [
                r"get_by_id\s*\(\s*\w+\s*\)",
                r"session\.get\s*\(\w+,\s*\w+\s*\)",
                r"Order\.objects\.get\s*\(pk=",
            ],
            "sqli": [
                r"execute\s*\(\s*f['\"]",
                r"execute\s*\(\s*query\s*=\s*f",
            ],
            "ssrf": [
                r"session\.get\s*\(\s*endpoint",
                r"client\.fetch\s*\(\s*target",
            ],
            "path_traversal": [
                r"anyio\.Path\s*\(\s*f['\"]",
            ],
            "auth_bypass": [
                r"request\.path_params\[.user_id.\]",
            ],
        }
        for pattern in unsafe_signals.get(vuln_class, []):
            if re.search(pattern, code, re.IGNORECASE):
                return "vulnerable"
        return "safe"
