"""
Audit report generation for agentaudit.

Generates Markdown and JSON reports from attack run results.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


class AuditReporter:
    """
    Generates security audit reports from agentaudit attack results.

    Supports Markdown (for GitHub/paper) and JSON (for CI/CD) output formats.

    Example:
        >>> loop = AttackLoop(target="activguard", mode="probe_bypass")
        >>> results = loop.run(vuln_class="idor")
        >>> reporter = AuditReporter()
        >>> print(reporter.markdown(results))
        >>> reporter.save(results, "audit_report.md")
    """

    def __init__(self, attacker_name: str = "agentaudit") -> None:
        """
        Initialise the reporter.

        Args:
            attacker_name: Name of the red-teaming tool generating the report.
        """
        if not isinstance(attacker_name, str):
            raise TypeError(f"attacker_name must be str, got {type(attacker_name).__name__}")
        self.attacker_name = attacker_name

    def markdown(self, results: dict[str, Any]) -> str:
        """
        Generate a Markdown audit report.

        Args:
            results: Return value from AttackLoop.run().

        Returns:
            Multi-section Markdown string.
        """
        self._validate_results(results)
        ts = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        bypass_rate = results.get("bypass_rate", 0.0)
        raw = results.get("raw_results", {})
        target = raw.get("target", "unknown")
        mode = raw.get("mode", results.get("mode", "unknown"))

        lines: list[str] = [
            f"# agentaudit Security Audit Report",
            f"",
            f"**Tool:** {self.attacker_name}  ",
            f"**Generated:** {ts}  ",
            f"**Target:** {target}  ",
            f"**Mode:** {mode}  ",
            f"",
            "## Summary",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Iterations | {results['iterations']} |",
            f"| Bypasses Found | **{results['bypasses_found']}** |",
            f"| Bypass Rate | {bypass_rate:.2%} |",
            f"| New redbench Entries | {len(results.get('new_redbench_entries', []))} |",
            "",
        ]

        if results["bypasses_found"] == 0:
            lines += [
                "## Result",
                "",
                f"No bypasses found in {results['iterations']} iterations. "
                f"The target system appears robust to the tested attack strategies.",
                "",
            ]
        else:
            lines += [
                f"## Bypass Findings ({results['bypasses_found']} found)",
                "",
            ]
            for i, finding in enumerate(results.get("findings", []), 1):
                lines += [
                    f"### Finding {i}: {finding.get('strategy', 'unknown')}",
                    "",
                    f"**Iteration:** {finding.get('iteration', '?')}  ",
                    f"**Vulnerability Class:** {finding.get('vuln_class', '?')}  ",
                    f"**Strategy:** {finding.get('strategy', '?')}  ",
                    "",
                    "**Bypass Code:**",
                    "```python",
                    finding.get("code", "").strip(),
                    "```",
                    "",
                    f"**Notes:** {finding.get('notes', '')}",
                    "",
                ]

        lines += [
            "## Adversarial Loop Diagram",
            "",
            "```",
            "agentaudit attacks ActivGuard",
            "    → finds bypass → adds to redbench",
            "    → ActivGuard retrained/updated",
            "    → agentaudit attacks again",
            "    → robustness improves over iterations",
            "```",
            "",
            "---",
            f"*Generated by agentaudit v0.1.0*",
        ]
        return "\n".join(lines)

    def to_json(self, results: dict[str, Any], indent: int = 2) -> str:
        """Serialise results to JSON string."""
        self._validate_results(results)
        output = {
            "tool": self.attacker_name,
            "timestamp": datetime.now(tz=timezone.utc).isoformat(),
            "bypasses_found": results["bypasses_found"],
            "iterations": results["iterations"],
            "bypass_rate": results["bypass_rate"],
            "findings": results.get("findings", []),
            "new_redbench_entries": results.get("new_redbench_entries", []),
        }
        return json.dumps(output, indent=indent)

    def save(self, results: dict[str, Any], output_path: str) -> None:
        """
        Save a report in the format inferred from the file extension.

        Args:
            results: Return value from AttackLoop.run().
            output_path: File path. .md → Markdown, .json → JSON.
        """
        if not isinstance(output_path, str) or not output_path.strip():
            raise ValueError("output_path must be a non-empty string")
        ext = Path(output_path).suffix.lower()
        if ext == ".json":
            content = self.to_json(results)
        else:
            content = self.markdown(results)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

    def _validate_results(self, results: dict[str, Any]) -> None:
        if not isinstance(results, dict):
            raise ValueError(f"results must be a dict, got {type(results).__name__}")
        required = {"bypasses_found", "iterations", "bypass_rate"}
        missing = required - set(results.keys())
        if missing:
            raise ValueError(f"results missing keys: {sorted(missing)}")
